name: Deployment Pipeline

on:
  pull_request:
    branches: [stage, qa]
    types: [opened, synchronize]

jobs:
  workflow-details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ℹ️ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "👀 This job is now running on a ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "㊢ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "👽 The workflow is now ready to test your code on the runner."

  avoid-redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redundant build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  create-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v3
        with:
          # Just fetching the last commit
          fetch-depth: 0

      - name: Set NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Installing Dependencies
        run: npm ci

      - name: Creating Artifacts Folder
        run: mkdir artifacts

      - name: Compressing App Code for Future Reuse
        run: tar -cvzf artifacts/memory-game.tar.gz --exclude=./artifacts .

      - name: Uploading Memory Game Code
        uses: actions/upload-artifact@v3
        with:
          name: memory-game.tar.gz
          path: artifacts/memory-game.tar.gz

  lint:
    needs: ['create-app']
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Memory Game Code
        uses: actions/download-artifact@v3
        with:
          name: memory-game.tar.gz

      - name: Decompressing Code
        run: tar -xvzf memory-game.tar.gz

      - name: Running Linter
        run: npm run lint

  build:
    needs: ['create-app']
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Memory Game App
        uses: actions/download-artifact@v3
        with:
          name: memory-game.tar.gz

      - name: Decompressing Code
        run: tar -xvzf memory-game.tar.gz

      - name: Building the Application
        run: npm run build --if-present

      - name: Uploading Memory Game Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    needs: ['lint', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Memory Game Code
        uses: actions/download-artifact@v3
        with:
          name: memory-game.tar.gz

      - name: Decompressing Code
        run: tar -xvzf memory-game.tar.gz

      - name: Downloading Memory Game Build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Running tests
        run: npm run test

  clean-artifacts:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - name: Cleaning Artifacts by Workflow Run
        uses: jimschubert/delete-artifacts-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          log_level: 'debug'
          min_bytes: '0'
          run_id: ${{ github.run_id }}
